import { domToCanvas } from 'modern-screenshot'
import { jsPDF } from 'jspdf'
import type { DashboardSummary } from './buildDashboardSummary'

export type DashboardPdfFilters = {
  month: string
  fuelType: string
  metroCity: string
}

export type ExportDashboardPdfOptions = {
  filters: DashboardPdfFilters
  summary: DashboardSummary
  chartElements: HTMLElement[]
}

const MARGIN_MM = 14
const FOOTER_OFFSET_MM = 10
const SECTION_GAP_MM = 6
const IMAGE_GAP_MM = 8

// Prefer modern-screenshot over html2canvas — Tailwind v4 oklch() breaks html2canvas.

function formatGeneratedOn(date: Date): string {
  return date.toLocaleString(undefined, {
    year: 'numeric',
    month: 'short',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
  })
}

function formatFilenameDate(date: Date): string {
  const year = date.getFullYear()
  const month = String(date.getMonth() + 1).padStart(2, '0')
  const day = String(date.getDate()).padStart(2, '0')
  return `${year}-${month}-${day}`
}

function displayFilterValue(value: string): string {
  return value.trim() ? value : 'All'
}

function toPdfSafeText(value: string): string {
  return value.replaceAll('₹', 'Rs. ')
}

function addFooter(pdf: jsPDF, pageWidth: number, pageHeight: number): void {
  pdf.setFont('helvetica', 'normal')
  pdf.setFontSize(9)
  pdf.setTextColor(100)
  pdf.text(
    'Generated by Fuel Price Dashboard',
    pageWidth / 2,
    pageHeight - FOOTER_OFFSET_MM,
    { align: 'center' },
  )
}

function ensureSpace(
  pdf: jsPDF,
  currentY: number,
  neededMm: number,
  pageWidth: number,
  pageHeight: number,
  contentBottom: number,
): number {
  if (currentY + neededMm <= contentBottom) {
    return currentY
  }

  addFooter(pdf, pageWidth, pageHeight)
  pdf.addPage()
  return MARGIN_MM
}

async function captureElement(element: HTMLElement): Promise<HTMLCanvasElement> {
  return domToCanvas(element, {
    scale: 2,
    backgroundColor: '#ffffff',
  })
}

function addCanvasImage(
  pdf: jsPDF,
  canvas: HTMLCanvasElement,
  startY: number,
  contentWidth: number,
  pageWidth: number,
  pageHeight: number,
  contentBottom: number,
): number {
  if (canvas.width === 0 || canvas.height === 0) {
    return startY
  }

  const imgWidth = contentWidth
  const imgHeight = (canvas.height * imgWidth) / canvas.width
  let cursorY = ensureSpace(
    pdf,
    startY,
    Math.min(imgHeight, contentBottom - MARGIN_MM) + IMAGE_GAP_MM,
    pageWidth,
    pageHeight,
    contentBottom,
  )

  let remainingHeight = imgHeight
  let sourceY = 0
  const pxPerMm = canvas.height / imgHeight

  while (remainingHeight > 1) {
    const availableHeight = contentBottom - cursorY

    if (availableHeight < 8) {
      addFooter(pdf, pageWidth, pageHeight)
      pdf.addPage()
      cursorY = MARGIN_MM
      continue
    }

    const sliceHeightMm = Math.min(remainingHeight, availableHeight)
    const sliceHeightPx = Math.max(1, Math.round(sliceHeightMm * pxPerMm))
    const sourceYPx = Math.min(
      canvas.height - 1,
      Math.round(sourceY * pxPerMm),
    )
    const safeSliceHeightPx = Math.min(sliceHeightPx, canvas.height - sourceYPx)

    const sliceCanvas = document.createElement('canvas')
    sliceCanvas.width = canvas.width
    sliceCanvas.height = safeSliceHeightPx

    const context = sliceCanvas.getContext('2d')
    if (!context) {
      break
    }

    context.drawImage(
      canvas,
      0,
      sourceYPx,
      canvas.width,
      safeSliceHeightPx,
      0,
      0,
      canvas.width,
      safeSliceHeightPx,
    )

    const sliceData = sliceCanvas.toDataURL('image/png')
    const renderedHeight = (safeSliceHeightPx * imgWidth) / canvas.width

    pdf.addImage(sliceData, 'PNG', MARGIN_MM, cursorY, imgWidth, renderedHeight)

    remainingHeight -= renderedHeight
    sourceY += renderedHeight
    cursorY += renderedHeight

    if (remainingHeight > 1) {
      addFooter(pdf, pageWidth, pageHeight)
      pdf.addPage()
      cursorY = MARGIN_MM
    }
  }

  return cursorY + IMAGE_GAP_MM
}

// Capture chart cards and assemble a multi-page PDF report.
export async function exportDashboardPdf({
  filters,
  summary,
  chartElements,
}: ExportDashboardPdfOptions): Promise<void> {
  const pdf = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  })

  const pageWidth = pdf.internal.pageSize.getWidth()
  const pageHeight = pdf.internal.pageSize.getHeight()
  const contentWidth = pageWidth - MARGIN_MM * 2
  const contentBottom = pageHeight - MARGIN_MM - 6
  const now = new Date()

  let cursorY = MARGIN_MM

  pdf.setFont('helvetica', 'bold')
  pdf.setFontSize(18)
  pdf.setTextColor(15, 23, 42)
  pdf.text('Fuel Price Dashboard Report', MARGIN_MM, cursorY)
  cursorY += 8

  pdf.setFont('helvetica', 'normal')
  pdf.setFontSize(11)
  pdf.setTextColor(71, 85, 105)
  pdf.text(`Generated On: ${formatGeneratedOn(now)}`, MARGIN_MM, cursorY)
  cursorY += SECTION_GAP_MM + 4

  pdf.setFont('helvetica', 'bold')
  pdf.setFontSize(13)
  pdf.setTextColor(15, 23, 42)
  pdf.text('Applied Filters', MARGIN_MM, cursorY)
  cursorY += 7

  pdf.setFont('helvetica', 'normal')
  pdf.setFontSize(11)
  pdf.setTextColor(51, 65, 85)
  const filterLines = [
    `Month: ${displayFilterValue(filters.month)}`,
    `Fuel Type: ${displayFilterValue(filters.fuelType)}`,
    `Metro City: ${displayFilterValue(filters.metroCity)}`,
  ]

  for (const line of filterLines) {
    pdf.text(line, MARGIN_MM + 2, cursorY)
    cursorY += 6
  }

  cursorY += SECTION_GAP_MM

  pdf.setFont('helvetica', 'bold')
  pdf.setFontSize(13)
  pdf.setTextColor(15, 23, 42)
  pdf.text('Summary Metrics', MARGIN_MM, cursorY)
  cursorY += 7

  pdf.setFont('helvetica', 'normal')
  pdf.setFontSize(11)
  pdf.setTextColor(51, 65, 85)
  const metricLines = [
    `Average Retail Selling Price: ${toPdfSafeText(summary.averagePrice)}`,
    `Highest Retail Selling Price: ${toPdfSafeText(summary.highestPrice)}`,
    `Lowest Retail Selling Price: ${toPdfSafeText(summary.lowestPrice)}`,
    `Total Records: ${summary.totalRecords}`,
  ]

  for (const line of metricLines) {
    pdf.text(line, MARGIN_MM + 2, cursorY)
    cursorY += 6
  }

  cursorY += SECTION_GAP_MM

  pdf.setFont('helvetica', 'bold')
  pdf.setFontSize(13)
  pdf.setTextColor(15, 23, 42)
  cursorY = ensureSpace(pdf, cursorY, 10, pageWidth, pageHeight, contentBottom)
  pdf.text('Charts', MARGIN_MM, cursorY)
  cursorY += 8

  for (const element of chartElements) {
    const canvas = await captureElement(element)
    cursorY = addCanvasImage(
      pdf,
      canvas,
      cursorY,
      contentWidth,
      pageWidth,
      pageHeight,
      contentBottom,
    )
  }

  addFooter(pdf, pageWidth, pageHeight)
  pdf.save(`fuel-price-dashboard-${formatFilenameDate(now)}.pdf`)
}
